version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # Defina uma senha
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_SSL_MODE: "DISABLED"
    ports:
      - "3306:3306"